apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}-service
  labels:
    env: {{ .Values.env }}
    owner: {{ .Values.owner }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "microservice.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
