nameOverride: mail-gateway
env: dev
owner: TimurKa
replicaCount: 1

image:
  repository: de4et/mail-gateway
  tag: latest

containerPort: 8080

configMapName: mail-services-config
secretName: mail-services-secret

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi
