apiVersion: v1
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env: prod
    owner: TimurKa
spec:
  type: LoadBalancer
  selector:
    project: mossad
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
      targetPort: 80
