---
# handlers file for kafka
# - name: Restart kafka
#   community.docker.docker_compose_v2:
#     project_src: /opt/
#     files: kafka-docker-compose.yml
#     state: restarted
#     wait: true
#     wait_timeout: 15
#   register: output
